# Generated by Django 4.2.6 on 2023-10-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_no', models.CharField(max_length=10, unique=True)),
                ('sender', models.CharField(default='', max_length=50)),
                ('reciever', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
