# Generated by Django 5.0.1 on 2024-02-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_email_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='recipients',
        ),
        migrations.AddField(
            model_name='email',
            name='recipients',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
