# Generated by Django 5.0.1 on 2024-02-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_remove_email_recipients_email_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.EmailField(default='Yash', max_length=254),
        ),
    ]
